"""Deterministic SQL wrappers and OpenAPI generation with no-write drift mode."""

import argparse
import hashlib
import json
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[4]
API = ROOT / "backend" / "src" / "app" / "apis" / "state"


def read_query(path: Path) -> str:
    """Parse PostgreSQL statements before producing wrappers; refuse SELECT *."""
    import sqlglot
    from sqlglot import exp

    text = path.read_text()
    statements = sqlglot.parse(text, read="postgres")
    if len(statements) != 1 or statements[0] is None:
        raise ValueError(f"expected one SQL statement: {path}")
    if statements[0].find(exp.Star):
        raise ValueError(f"wildcard projection forbidden: {path}")
    if not text.lstrip().startswith("--"):
        raise ValueError(f"missing SQL processing summary: {path}")
    return text


def generate_outputs(openapi_only: bool = False) -> dict[Path, str]:
    """Render wrappers from declared SQL sources and OpenAPI from actual routes."""
    from app.main import create_app

    openapi = (
        json.dumps(create_app().openapi(), ensure_ascii=False, indent=2, sort_keys=True) + "\n"
    )
    if openapi_only:
        return {ROOT / "backend/openapi.gen.json": openapi}
    select = read_query(API / "get_state/sql/001_select_state.sql")
    insert = read_query(API / "put_state/sql/001_insert_state.sql")
    update = read_query(API / "put_state/sql/002_update_state.sql")
    digest = hashlib.sha256((select + insert + update).encode()).hexdigest()
    header = f"# Generated by app-docs. Do not edit.\n# SQL SHA256: {digest}\n"
    get_source = (
        header
        + f'''from dataclasses import dataclass

from psycopg import Connection
from psycopg.rows import class_row
from pydantic import JsonValue

SELECT_STATE = """{select}"""


@dataclass
class StoredState:
    revision: int
    payload: dict[str, JsonValue]


def select_state(connection: Connection[tuple[object, ...]], subject: str) -> StoredState | None:
    with connection.cursor(row_factory=class_row(StoredState)) as cursor:
        cursor.execute(SELECT_STATE, {{"subject": subject}})
        return cursor.fetchone()
'''
    )
    put_source = (
        header
        + f'''from psycopg import Connection
from psycopg.types.json import Jsonb
from pydantic import JsonValue

INSERT_STATE = """{insert}"""
UPDATE_STATE = """{update}"""


def insert_state(connection: Connection[tuple[object, ...]], subject: str,
                 payload: dict[str, JsonValue]) -> None:
    connection.execute(INSERT_STATE, {{"subject": subject, "payload": Jsonb(payload)}})


def update_state(connection: Connection[tuple[object, ...]], subject: str,
                 revision: int, payload: dict[str, JsonValue]) -> bool:
    cursor = connection.execute(UPDATE_STATE, {{"subject": subject, "revision": revision,
                                              "payload": Jsonb(payload)}})
    return cursor.rowcount == 1
'''
    )
    # Use the locked formatter so checked-in generated Python also satisfies Ruff.
    from subprocess import run

    formatted: list[str] = []
    formatter = shutil.which("ruff")
    if formatter is None:
        raise RuntimeError("locked Ruff formatter is required")
    for source in (get_source, put_source):
        result = run(  # noqa: S603 -- fixed locked formatter, source sent on stdin; no shell
            [formatter, "format", "--stdin-filename", "queries.py", "-"],
            input=source,
            text=True,
            capture_output=True,
            check=True,
        )
        formatted.append(result.stdout)
    return {
        API / "get_state/generated/queries.py": formatted[0],
        API / "put_state/generated/queries.py": formatted[1],
        ROOT / "backend/openapi.gen.json": openapi,
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--openapi-only", action="store_true")
    args = parser.parse_args()
    outputs = generate_outputs(openapi_only=args.openapi_only)
    stale: list[str] = []
    for path, text in outputs.items():
        if not path.is_file() or path.read_text() != text:
            if args.check:
                stale.append(str(path.relative_to(ROOT)))
            else:
                path.parent.mkdir(parents=True, exist_ok=True)
                temporary = path.with_suffix(path.suffix + ".tmp")
                temporary.write_text(text)
                temporary.replace(path)
    if stale:
        print("Generated drift: " + ", ".join(stale))
        return 1
    print("SQL wrappers and OpenAPI are current.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
