# generate_backup_api.py による自動生成。直接編集しない。
from typing import Any

TABLES: dict[str, Any] = {
    "user_preference": {
        "label": "ユーザーの嗜好",
        "columns": ["id", "created_at", "user_id", "option_id", "weight"],
        "json_columns": [],
        "bigint_columns": [],
        "references": [
            {"column": "user_id", "table": "app_user"},
            {"column": "option_id", "table": "axis_option"},
        ],
    },
    "user_exclusion": {
        "label": "避けたい食材・物質",
        "columns": ["id", "created_at", "user_id", "food_id", "allergen_id", "strict"],
        "json_columns": [],
        "bigint_columns": [],
        "references": [
            {"column": "user_id", "table": "app_user"},
            {"column": "food_id", "table": "food"},
            {"column": "allergen_id", "table": "allergen"},
        ],
    },
    "user_recipe_event": {
        "label": "提案・調理履歴",
        "columns": [
            "id",
            "created_at",
            "user_id",
            "recipe_version_id",
            "kind",
            "occurred_at",
            "request_key",
        ],
        "json_columns": [],
        "bigint_columns": [],
        "references": [
            {"column": "user_id", "table": "app_user"},
            {"column": "recipe_version_id", "table": "recipe_version"},
        ],
    },
    "menu": {
        "label": "献立",
        "columns": ["id", "created_at", "user_id", "name", "servings", "revision"],
        "json_columns": [],
        "bigint_columns": [],
        "references": [{"column": "user_id", "table": "app_user"}],
    },
    "menu_item": {
        "label": "献立の料理",
        "columns": [
            "id",
            "created_at",
            "menu_id",
            "recipe_version_id",
            "servings",
            "role_option_id",
            "position",
        ],
        "json_columns": [],
        "bigint_columns": [],
        "references": [
            {"column": "menu_id", "table": "menu"},
            {"column": "recipe_version_id", "table": "recipe_version"},
            {"column": "role_option_id", "table": "axis_option"},
        ],
    },
    "menu_ingredient_override": {
        "label": "献立別材料確定",
        "columns": [
            "id",
            "created_at",
            "menu_item_id",
            "ingredient_line_id",
            "selected",
            "amount",
            "form_id",
            "product_version_id",
        ],
        "json_columns": [],
        "bigint_columns": [],
        "references": [
            {"column": "menu_item_id", "table": "menu_item"},
            {"column": "ingredient_line_id", "table": "recipe_ingredient"},
            {"column": "form_id", "table": "food_form"},
            {"column": "product_version_id", "table": "product_version"},
        ],
    },
    "kitchen_resource": {
        "label": "キッチンの実資源",
        "columns": [
            "id",
            "created_at",
            "user_id",
            "resource_type_id",
            "name",
            "capacity",
            "quantity",
            "active",
        ],
        "json_columns": [],
        "bigint_columns": [],
        "references": [
            {"column": "user_id", "table": "app_user"},
            {"column": "resource_type_id", "table": "resource_type"},
        ],
    },
    "cooking_session": {
        "label": "調理計画実行",
        "columns": [
            "id",
            "created_at",
            "menu_id",
            "menu_revision",
            "status",
            "target_at",
            "planner_version",
            "input_snapshot",
            "input_hash",
            "current_task_index",
        ],
        "json_columns": ["input_snapshot"],
        "bigint_columns": [],
        "references": [{"column": "menu_id", "table": "menu"}],
    },
    "session_task": {
        "label": "展開済み工程",
        "columns": [
            "id",
            "created_at",
            "session_id",
            "menu_item_id",
            "step_id",
            "batch_no",
            "planned_start_s",
            "planned_end_s",
            "status",
            "actual_start_at",
            "actual_end_at",
            "timer_started_at",
            "timer_duration_s",
            "duration_source",
            "confirmed_duration_s",
        ],
        "json_columns": [],
        "bigint_columns": [],
        "references": [
            {"column": "session_id", "table": "cooking_session"},
            {"column": "menu_item_id", "table": "menu_item"},
            {"column": "step_id", "table": "recipe_step"},
        ],
    },
    "task_dependency": {
        "label": "献立展開後依存",
        "columns": [
            "id",
            "created_at",
            "before_task_id",
            "after_task_id",
            "min_lag_s",
            "max_lag_s",
            "reason",
        ],
        "json_columns": [],
        "bigint_columns": [],
        "references": [
            {"column": "before_task_id", "table": "session_task"},
            {"column": "after_task_id", "table": "session_task"},
        ],
    },
    "resource_reservation": {
        "label": "資源の予約",
        "columns": ["id", "created_at", "task_id", "resource_id", "start_s", "end_s", "quantity"],
        "json_columns": [],
        "bigint_columns": [],
        "references": [
            {"column": "task_id", "table": "session_task"},
            {"column": "resource_id", "table": "kitchen_resource"},
        ],
    },
    "ingredient_total": {
        "label": "献立材料集計結果",
        "columns": [
            "id",
            "created_at",
            "session_id",
            "form_id",
            "product_version_id",
            "unit_id",
            "required_amount",
            "quality",
            "calculation_version",
            "actual_amount",
            "consumption_outcome",
        ],
        "json_columns": [],
        "bigint_columns": [],
        "references": [
            {"column": "session_id", "table": "cooking_session"},
            {"column": "form_id", "table": "food_form"},
            {"column": "product_version_id", "table": "product_version"},
            {"column": "unit_id", "table": "unit"},
        ],
    },
    "pantry_lot": {
        "label": "手持ち食材ロット",
        "columns": [
            "id",
            "created_at",
            "user_id",
            "form_id",
            "product_version_id",
            "amount",
            "unit_id",
            "expires_on",
            "opened_at",
            "location",
            "priority",
            "status",
            "source_import_id",
            "quantity_quality",
            "original_form_id",
            "original_amount",
            "original_unit_id",
            "updated_at",
            "edited",
        ],
        "json_columns": [],
        "bigint_columns": [],
        "references": [
            {"column": "user_id", "table": "app_user"},
            {"column": "form_id", "table": "food_form"},
            {"column": "product_version_id", "table": "product_version"},
            {"column": "unit_id", "table": "unit"},
            {"column": "source_import_id", "table": "receipt_import"},
            {"column": "original_form_id", "table": "food_form"},
            {"column": "original_unit_id", "table": "unit"},
        ],
    },
    "shopping_item": {
        "label": "買い物行",
        "columns": [
            "id",
            "created_at",
            "session_id",
            "total_id",
            "product_version_id",
            "net_shortage",
            "package_count",
            "surplus_amount",
            "checked",
            "client_key",
            "checked_at",
            "archived",
        ],
        "json_columns": [],
        "bigint_columns": [],
        "references": [
            {"column": "session_id", "table": "cooking_session"},
            {"column": "total_id", "table": "ingredient_total"},
            {"column": "product_version_id", "table": "product_version"},
        ],
    },
    "receipt_import": {
        "label": "レシート読取・在庫登録の処理単位",
        "columns": [
            "id",
            "created_at",
            "user_id",
            "file_sha256",
            "idempotency_key",
            "status",
            "revision",
            "committed_at",
            "reverted_at",
            "undo_preserved_count",
        ],
        "json_columns": [],
        "bigint_columns": ["revision"],
        "references": [{"column": "user_id", "table": "app_user"}],
    },
    "receipt_line": {
        "label": "レシートの商品候補と確定した在庫の対応",
        "columns": [
            "id",
            "created_at",
            "import_id",
            "line_no",
            "raw_name",
            "form_id",
            "product_version_id",
            "amount",
            "unit_id",
            "decision",
            "pantry_lot_id",
        ],
        "json_columns": [],
        "bigint_columns": [],
        "references": [
            {"column": "import_id", "table": "receipt_import"},
            {"column": "form_id", "table": "food_form"},
            {"column": "product_version_id", "table": "product_version"},
            {"column": "unit_id", "table": "unit"},
            {"column": "pantry_lot_id", "table": "pantry_lot"},
        ],
    },
    "user_food": {
        "label": "利用者が追加した独自食材の所有",
        "columns": ["id", "created_at", "user_id", "food_id"],
        "json_columns": [],
        "bigint_columns": [],
        "references": [
            {"column": "user_id", "table": "app_user"},
            {"column": "food_id", "table": "food"},
        ],
    },
    "user_pantry_food": {
        "label": "利用者が常備すると設定した食材",
        "columns": ["id", "created_at", "user_id", "food_id"],
        "json_columns": [],
        "bigint_columns": [],
        "references": [
            {"column": "user_id", "table": "app_user"},
            {"column": "food_id", "table": "food"},
        ],
    },
    "pantry_consumption": {
        "label": "調理による在庫消費の冪等台帳",
        "columns": ["id", "created_at", "user_id", "session_id", "lot_id", "amount", "unit_id"],
        "json_columns": [],
        "bigint_columns": [],
        "references": [
            {"column": "user_id", "table": "app_user"},
            {"column": "session_id", "table": "cooking_session"},
            {"column": "lot_id", "table": "pantry_lot"},
            {"column": "unit_id", "table": "unit"},
        ],
    },
    "user_shopping_check": {
        "label": "調理前の買い物確認",
        "columns": [
            "id",
            "created_at",
            "user_id",
            "key",
            "signature",
            "food_id",
            "amount",
            "unit_id",
            "checked_at",
            "archived",
        ],
        "json_columns": [],
        "bigint_columns": [],
        "references": [
            {"column": "user_id", "table": "app_user"},
            {"column": "food_id", "table": "food"},
            {"column": "unit_id", "table": "unit"},
        ],
    },
    "catalog_release": {
        "label": "カタログ公開版",
        "columns": ["id", "created_at", "version", "manifest_hash", "published_at", "owner_id"],
        "json_columns": [],
        "bigint_columns": [],
        "references": [{"column": "owner_id", "table": "app_user"}],
    },
    "food": {
        "label": "購入・利用食材概念",
        "columns": [
            "id",
            "created_at",
            "code",
            "name",
            "kind",
            "parent_id",
            "release_id",
            "status",
            "owner_id",
        ],
        "json_columns": [],
        "bigint_columns": [],
        "references": [
            {"column": "parent_id", "table": "food"},
            {"column": "release_id", "table": "catalog_release"},
            {"column": "owner_id", "table": "app_user"},
        ],
    },
    "food_alias": {
        "label": "食材別名",
        "columns": ["id", "created_at", "food_id", "alias", "locale"],
        "json_columns": [],
        "bigint_columns": [],
        "references": [{"column": "food_id", "table": "food"}],
    },
    "food_form": {
        "label": "食材形態",
        "columns": [
            "id",
            "created_at",
            "food_id",
            "name",
            "state",
            "base_unit_id",
            "quantity_basis",
            "status",
        ],
        "json_columns": [],
        "bigint_columns": [],
        "references": [
            {"column": "food_id", "table": "food"},
            {"column": "base_unit_id", "table": "unit"},
        ],
    },
    "food_axis_option": {
        "label": "食材の分類属性",
        "columns": ["id", "created_at", "food_id", "option_id"],
        "json_columns": [],
        "bigint_columns": [],
        "references": [
            {"column": "food_id", "table": "food"},
            {"column": "option_id", "table": "axis_option"},
        ],
    },
    "product": {
        "label": "市販商品識別",
        "columns": ["id", "created_at", "food_id", "brand", "name", "gtin", "status"],
        "json_columns": [],
        "bigint_columns": [],
        "references": [{"column": "food_id", "table": "food"}],
    },
    "conversion": {
        "label": "食材形態別換算",
        "columns": [
            "id",
            "created_at",
            "form_id",
            "from_unit_id",
            "to_unit_id",
            "factor",
            "quality",
            "source_id",
            "conditions",
            "release_id",
        ],
        "json_columns": [],
        "bigint_columns": [],
        "references": [
            {"column": "form_id", "table": "food_form"},
            {"column": "from_unit_id", "table": "unit"},
            {"column": "to_unit_id", "table": "unit"},
            {"column": "source_id", "table": "source_record"},
            {"column": "release_id", "table": "catalog_release"},
        ],
    },
    "food_allergen": {
        "label": "食材アレルゲン知識",
        "columns": ["id", "created_at", "form_id", "allergen_id", "presence", "source_id"],
        "json_columns": [],
        "bigint_columns": [],
        "references": [
            {"column": "form_id", "table": "food_form"},
            {"column": "allergen_id", "table": "allergen"},
            {"column": "source_id", "table": "source_record"},
        ],
    },
    "product_version": {
        "label": "商品仕様版",
        "columns": [
            "id",
            "created_at",
            "product_id",
            "version",
            "form_id",
            "net_amount",
            "unit_id",
            "drain_amount",
            "source_id",
            "preparation_note",
            "valid_from",
        ],
        "json_columns": [],
        "bigint_columns": [],
        "references": [
            {"column": "product_id", "table": "product"},
            {"column": "form_id", "table": "food_form"},
            {"column": "unit_id", "table": "unit"},
            {"column": "source_id", "table": "source_record"},
        ],
    },
    "product_component": {
        "label": "セット内構成品",
        "columns": [
            "id",
            "created_at",
            "product_version_id",
            "form_id",
            "name",
            "amount",
            "unit_id",
            "quality",
        ],
        "json_columns": [],
        "bigint_columns": [],
        "references": [
            {"column": "product_version_id", "table": "product_version"},
            {"column": "form_id", "table": "food_form"},
            {"column": "unit_id", "table": "unit"},
        ],
    },
    "product_allergen": {
        "label": "商品表示アレルゲン",
        "columns": [
            "id",
            "created_at",
            "product_version_id",
            "allergen_id",
            "presence",
            "source_id",
        ],
        "json_columns": [],
        "bigint_columns": [],
        "references": [
            {"column": "product_version_id", "table": "product_version"},
            {"column": "allergen_id", "table": "allergen"},
            {"column": "source_id", "table": "source_record"},
        ],
    },
    "product_preparation_rule": {
        "label": "商品固有の調理条件",
        "columns": [
            "id",
            "created_at",
            "product_version_id",
            "operation_id",
            "allowed",
            "use_original_container",
            "parameter_contract",
            "source_id",
        ],
        "json_columns": ["parameter_contract"],
        "bigint_columns": [],
        "references": [
            {"column": "product_version_id", "table": "product_version"},
            {"column": "operation_id", "table": "operation"},
            {"column": "source_id", "table": "source_record"},
        ],
    },
    "nutrition_fact": {
        "label": "形態・商品別栄養値",
        "columns": [
            "id",
            "created_at",
            "form_id",
            "product_version_id",
            "nutrient_id",
            "amount",
            "basis_amount",
            "basis_unit_id",
            "source_id",
        ],
        "json_columns": [],
        "bigint_columns": [],
        "references": [
            {"column": "form_id", "table": "food_form"},
            {"column": "product_version_id", "table": "product_version"},
            {"column": "nutrient_id", "table": "nutrient"},
            {"column": "basis_unit_id", "table": "unit"},
            {"column": "source_id", "table": "source_record"},
        ],
    },
    "form_yield": {
        "label": "処理歩留まり",
        "columns": [
            "id",
            "created_at",
            "input_form_id",
            "output_form_id",
            "yield_ratio",
            "source_id",
            "quality",
            "conditions",
        ],
        "json_columns": [],
        "bigint_columns": [],
        "references": [
            {"column": "input_form_id", "table": "food_form"},
            {"column": "output_form_id", "table": "food_form"},
            {"column": "source_id", "table": "source_record"},
        ],
    },
}
OWNED: tuple[str, ...] = (
    "user_preference",
    "user_exclusion",
    "user_recipe_event",
    "menu",
    "menu_item",
    "menu_ingredient_override",
    "kitchen_resource",
    "cooking_session",
    "session_task",
    "task_dependency",
    "resource_reservation",
    "ingredient_total",
    "pantry_lot",
    "shopping_item",
    "receipt_import",
    "receipt_line",
    "user_food",
    "user_pantry_food",
    "pantry_consumption",
    "user_shopping_check",
)
PRIVATE: tuple[str, ...] = (
    "catalog_release",
    "food",
    "food_alias",
    "food_form",
    "food_axis_option",
    "product",
    "conversion",
    "food_allergen",
    "product_version",
    "product_component",
    "product_allergen",
    "product_preparation_rule",
    "nutrition_fact",
    "form_yield",
)
DELETE_ORDER: tuple[str, ...] = (
    "resource_reservation",
    "task_dependency",
    "shopping_item",
    "pantry_consumption",
    "receipt_line",
    "menu_ingredient_override",
    "session_task",
    "ingredient_total",
    "cooking_session",
    "menu_item",
    "menu",
    "kitchen_resource",
    "pantry_lot",
    "receipt_import",
    "user_preference",
    "user_exclusion",
    "user_recipe_event",
    "user_food",
    "user_pantry_food",
    "user_shopping_check",
    "product_preparation_rule",
    "product_allergen",
    "nutrition_fact",
    "food_allergen",
    "form_yield",
    "conversion",
    "product_component",
    "product_version",
    "product",
    "food_axis_option",
    "food_alias",
    "food_form",
    "food",
    "catalog_release",
)
INSERT_ORDER: tuple[str, ...] = (
    "catalog_release",
    "food",
    "food_form",
    "food_alias",
    "food_axis_option",
    "product",
    "product_version",
    "product_component",
    "conversion",
    "food_allergen",
    "product_allergen",
    "product_preparation_rule",
    "nutrition_fact",
    "form_yield",
    "user_preference",
    "user_exclusion",
    "user_recipe_event",
    "menu",
    "menu_item",
    "menu_ingredient_override",
    "kitchen_resource",
    "cooking_session",
    "session_task",
    "task_dependency",
    "resource_reservation",
    "ingredient_total",
    "shopping_item",
    "receipt_import",
    "pantry_lot",
    "receipt_line",
    "user_food",
    "user_pantry_food",
    "pantry_consumption",
    "user_shopping_check",
)
